---
title: "ANOVA: Comparing 3+ Population Means"
format:
  pdf:
    geometry:
      - top=.75in
      - left=.75in
      - right=.75in
      - bottom=.75in
---

<!-- # Overview of R Markdown files -->

In this class, you will work with your group to explore one-way ANOVA models by completing **activities 19-27 from the textbook**. While you work through this activity, make sure that all group members are engaged and contribute ideas, and also follow the code. The [R Manual](https://stat230.github.io/r-manual-kuiper/02-chapter02.html) has useful R code for today's activities.


## The ANOVA Model

As you saw before class, the ANOVA model is given by 
$$y_{ij} = \mu + \alpha_i + \varepsilon_{ij}, \quad \text{for }i = 1, \ldots, I \quad \text{and } j=1, 2, \ldots, n_i, \quad \text{where } \varepsilon_{ij} \overset{iid}{\sim} \mathcal{N}(0, \sigma^2)$$
Once we have data in hand, we can use it to estimate the model parameters of interest. When interest centers on discerning a different between group means the **effects**, $\alpha_i$, are of primary interest.

**Complete activities 19-22**. These activities lead you through estimating the effects (or effect sizes) for the two treatment groups (color distractor and standard game) and visualizing the fitted model using a **main effects plot**. Activity 22 then has you calculate a residual.


The necessary assumptions/conditions for the one-way ANOVA model are:

1. the error terms are i.i.d.
1. the error terms follow a normal distribution
1. the error terms have mean 0
1. the population variance is the same for each group (i.e., within each factor level)




Shonda recommends 16-27...
